import { useState, useEffect } from "react";
import { invoke } from "@tauri-apps/api/core";

interface VideoFile {
  name: string;
  path: string;
  size: string;
  modified: string;
}

interface GeneratorConfig {
  type: "general_knowledge" | "spot_difference" | "odd_one_out" | "emoji_word";
  numQuestions?: number;
  questionTime?: number;
  answerTime?: number;
  outputFilename?: string;
}

interface AutomationStatus {
  running: boolean;
  videos_generated: number;
  videos_uploaded: number;
  current_action: string;
  last_error: string | null;
}

const VIDEO_TYPES = [
  {
    id: "general_knowledge",
    name: "General Knowledge Quiz",
    icon: "🧠",
    description: "Multiple choice quiz with TTS narration",
  },
  {
    id: "spot_difference",
    name: "Spot the Difference",
    icon: "🔍",
    description: "Side-by-side image puzzles",
  },
  {
    id: "odd_one_out",
    name: "Odd One Out",
    icon: "🎯",
    description: "Find the different item in a grid",
  },
  {
    id: "emoji_word",
    name: "Emoji Word Puzzle",
    icon: "😀",
    description: "Guess the word from emojis",
  },
];

export default function Videos() {
  const [videos, setVideos] = useState<VideoFile[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [uploading, setUploading] = useState<string | null>(null);
  const [showAutomation, setShowAutomation] = useState(false);
  const [automationStatus, setAutomationStatus] = useState<AutomationStatus | null>(null);
  const [numVideosToGenerate, setNumVideosToGenerate] = useState(6); // YouTube API limit: 6/day
  const [message, setMessage] = useState<{
    type: "success" | "error";
    text: string;
  } | null>(null);
  const [showGenerator, setShowGenerator] = useState(false);
  const [generatorConfig, setGeneratorConfig] = useState<GeneratorConfig>({
    type: "general_knowledge",
    numQuestions: 100,
    questionTime: 5,
    answerTime: 3,
    outputFilename: "",
  });

  useEffect(() => {
    loadVideos();
    // Poll automation status
    const interval = setInterval(async () => {
      try {
        const status = await invoke<AutomationStatus>("get_automation_status");
        setAutomationStatus(status);
        if (status.running) {
          loadVideos(); // Refresh video list while automation runs
        }
      } catch (e) {
        console.error("Failed to get automation status:", e);
      }
    }, 2000);
    return () => clearInterval(interval);
  }, []);

  const startAutomation = async () => {
    try {
      await invoke("start_automation", {
        config: generatorConfig,
        numVideos: numVideosToGenerate,
      });
      setMessage({ type: "success", text: "Automation started!" });
      setShowAutomation(false);
    } catch (error) {
      setMessage({ type: "error", text: `Failed to start: ${error}` });
    }
  };

  const stopAutomation = async () => {
    try {
      await invoke("stop_automation");
      setMessage({ type: "success", text: "Automation stopped" });
    } catch (error) {
      setMessage({ type: "error", text: `Failed to stop: ${error}` });
    }
  };

  const loadVideos = async () => {
    setLoading(true);
    try {
      const result = await invoke<VideoFile[]>("list_videos");
      setVideos(result);
    } catch (error) {
      console.error("Failed to load videos:", error);
      setMessage({ type: "error", text: `Failed to load videos: ${error}` });
    } finally {
      setLoading(false);
    }
  };

  const generateVideo = async () => {
    setGenerating(true);
    setMessage(null);
    try {
      const result = await invoke<string>("generate_video", {
        config: generatorConfig,
      });
      setMessage({ type: "success", text: `Video generated: ${result}` });
      setShowGenerator(false);
      loadVideos();
    } catch (error) {
      setMessage({ type: "error", text: `Generation failed: ${error}` });
    } finally {
      setGenerating(false);
    }
  };

  const uploadToYouTube = async (video: VideoFile) => {
    setUploading(video.name);
    setMessage(null);
    try {
      const result = await invoke<string>("upload_to_youtube", {
        videoPath: video.path,
        title: video.name.replace(".mp4", ""),
        description: `Generated by SharvaYoutubePro`,
      });
      setMessage({
        type: "success",
        text: `Uploaded successfully! Video ID: ${result}`,
      });
    } catch (error) {
      setMessage({ type: "error", text: `Upload failed: ${error}` });
    } finally {
      setUploading(null);
    }
  };

  const deleteVideo = async (video: VideoFile) => {
    if (!confirm(`Delete ${video.name}?`)) return;

    try {
      await invoke("delete_video", { videoPath: video.path });
      setMessage({ type: "success", text: "Video deleted" });
      loadVideos();
    } catch (error) {
      setMessage({ type: "error", text: `Delete failed: ${error}` });
    }
  };

  return (
    <div className="max-w-6xl mx-auto">
      <div className="flex items-center justify-between mb-8">
        <h1 className="text-3xl font-bold text-white">Videos</h1>
        <div className="flex gap-3">
          <button
            onClick={loadVideos}
            className="px-4 py-2 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-colors flex items-center gap-2"
          >
            <span>🔄</span> Refresh
          </button>
          <button
            onClick={() => setShowGenerator(true)}
            className="px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-lg transition-colors flex items-center gap-2"
          >
            <span>➕</span> Generate Video
          </button>
          {automationStatus?.running ? (
            <button
              onClick={stopAutomation}
              className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg transition-colors flex items-center gap-2"
            >
              <span>⏹️</span> Stop Automation
            </button>
          ) : (
            <button
              onClick={() => setShowAutomation(true)}
              className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors flex items-center gap-2"
            >
              <span>🤖</span> Auto Generate
            </button>
          )}
        </div>
      </div>

      {/* Automation Status Bar */}
      {automationStatus?.running && (
        <div className="mb-6 p-4 bg-green-500/20 border border-green-500 rounded-lg">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="animate-spin text-2xl">🔄</div>
              <div>
                <p className="text-green-200 font-medium">{automationStatus.current_action}</p>
                <p className="text-green-300 text-sm">
                  Generated: {automationStatus.videos_generated} | Uploaded: {automationStatus.videos_uploaded}
                </p>
              </div>
            </div>
            <button
              onClick={stopAutomation}
              className="px-3 py-1 bg-red-600 hover:bg-red-700 text-white rounded-lg text-sm"
            >
              Stop
            </button>
          </div>
          {automationStatus.last_error && (
            <p className="mt-2 text-red-300 text-sm">Last error: {automationStatus.last_error}</p>
          )}
        </div>
      )}

      {message && (
        <div
          className={`mb-6 p-4 rounded-lg ${
            message.type === "success"
              ? "bg-green-500/20 border border-green-500 text-green-200"
              : "bg-red-500/20 border border-red-500 text-red-200"
          }`}
        >
          {message.text}
        </div>
      )}

      {/* Generator Modal */}
      {showGenerator && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-slate-800 rounded-2xl p-6 max-w-lg w-full mx-4 border border-white/20">
            <h2 className="text-xl font-bold text-white mb-4">
              Generate New Video
            </h2>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Video Type
                </label>
                <div className="grid grid-cols-2 gap-2">
                  {VIDEO_TYPES.map((vt) => (
                    <button
                      key={vt.id}
                      onClick={() =>
                        setGeneratorConfig((c) => ({
                          ...c,
                          type: vt.id as GeneratorConfig["type"],
                        }))
                      }
                      className={`p-3 rounded-lg text-left transition-colors ${
                        generatorConfig.type === vt.id
                          ? "bg-purple-600 text-white"
                          : "bg-white/10 text-slate-300 hover:bg-white/20"
                      }`}
                    >
                      <span className="text-xl">{vt.icon}</span>
                      <span className="ml-2 text-sm">{vt.name}</span>
                    </button>
                  ))}
                </div>
              </div>

              {generatorConfig.type === "general_knowledge" && (
                <>
                  <div>
                    <label className="block text-sm font-medium text-slate-300 mb-2">
                      Number of Questions
                    </label>
                    <input
                      type="number"
                      min="1"
                      max="500"
                      value={generatorConfig.numQuestions || 100}
                      onChange={(e) =>
                        setGeneratorConfig((c) => ({
                          ...c,
                          numQuestions: parseInt(e.target.value) || 100,
                        }))
                      }
                      className="w-full px-4 py-2 bg-black/30 border border-white/20 rounded-lg text-white"
                    />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        Question Time (sec)
                      </label>
                      <input
                        type="number"
                        min="3"
                        max="30"
                        value={generatorConfig.questionTime || 5}
                        onChange={(e) =>
                          setGeneratorConfig((c) => ({
                            ...c,
                            questionTime: parseInt(e.target.value) || 5,
                          }))
                        }
                        className="w-full px-4 py-2 bg-black/30 border border-white/20 rounded-lg text-white"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        Answer Time (sec)
                      </label>
                      <input
                        type="number"
                        min="1"
                        max="10"
                        value={generatorConfig.answerTime || 3}
                        onChange={(e) =>
                          setGeneratorConfig((c) => ({
                            ...c,
                            answerTime: parseInt(e.target.value) || 3,
                          }))
                        }
                        className="w-full px-4 py-2 bg-black/30 border border-white/20 rounded-lg text-white"
                      />
                    </div>
                  </div>
                </>
              )}

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Output Filename (optional)
                </label>
                <input
                  type="text"
                  placeholder="e.g., my_quiz.mp4"
                  value={generatorConfig.outputFilename || ""}
                  onChange={(e) =>
                    setGeneratorConfig((c) => ({
                      ...c,
                      outputFilename: e.target.value,
                    }))
                  }
                  className="w-full px-4 py-2 bg-black/30 border border-white/20 rounded-lg text-white placeholder-slate-500"
                />
              </div>

              <div className="flex gap-3 pt-4">
                <button
                  onClick={() => setShowGenerator(false)}
                  className="flex-1 py-3 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={generateVideo}
                  disabled={generating}
                  className="flex-1 py-3 bg-purple-600 hover:bg-purple-700 disabled:bg-purple-600/50 text-white rounded-lg transition-colors"
                >
                  {generating ? "Generating..." : "Generate"}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Automation Modal */}
      {showAutomation && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-slate-800 rounded-2xl p-6 max-w-lg w-full mx-4 border border-white/20">
            <h2 className="text-xl font-bold text-white mb-4">
              🤖 Auto Generate & Upload
            </h2>

            <div className="space-y-4">
              <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-4">
                <p className="text-yellow-200 text-sm">
                  <strong>YouTube API Limit:</strong> 6 videos per day.
                  Each video uses unique questions that won't repeat.
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Number of Videos (max 6/day)
                </label>
                <input
                  type="number"
                  min="1"
                  max="6"
                  value={numVideosToGenerate}
                  onChange={(e) => setNumVideosToGenerate(Math.min(6, parseInt(e.target.value) || 1))}
                  className="w-full px-4 py-2 bg-black/30 border border-white/20 rounded-lg text-white"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Questions per Video
                </label>
                <input
                  type="number"
                  min="1"
                  max="500"
                  value={generatorConfig.numQuestions || 100}
                  onChange={(e) =>
                    setGeneratorConfig((c) => ({
                      ...c,
                      numQuestions: parseInt(e.target.value) || 100,
                    }))
                  }
                  className="w-full px-4 py-2 bg-black/30 border border-white/20 rounded-lg text-white"
                />
              </div>

              <div className="bg-slate-700/50 rounded-lg p-3">
                <p className="text-slate-300 text-sm">
                  Total questions needed: <strong>{numVideosToGenerate * (generatorConfig.numQuestions || 100)}</strong>
                </p>
              </div>

              <div className="flex gap-3 pt-4">
                <button
                  onClick={() => setShowAutomation(false)}
                  className="flex-1 py-3 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={startAutomation}
                  className="flex-1 py-3 bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors"
                >
                  🚀 Start Automation
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Videos List */}
      {loading ? (
        <div className="text-center text-white py-12">Loading videos...</div>
      ) : videos.length === 0 ? (
        <div className="text-center py-12">
          <div className="text-6xl mb-4">🎬</div>
          <p className="text-slate-300 text-lg">No videos found</p>
          <p className="text-slate-400 text-sm mt-2">
            Generate your first video to get started
          </p>
        </div>
      ) : (
        <div className="grid gap-4">
          {videos.map((video) => (
            <div
              key={video.path}
              className="bg-white/10 backdrop-blur-lg rounded-xl p-4 border border-white/20 flex items-center gap-4"
            >
              <div className="w-16 h-16 bg-purple-600/30 rounded-lg flex items-center justify-center text-3xl">
                🎬
              </div>
              <div className="flex-1 min-w-0">
                <h3 className="text-white font-medium truncate">{video.name}</h3>
                <p className="text-slate-400 text-sm">
                  {video.size} • {video.modified}
                </p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => uploadToYouTube(video)}
                  disabled={uploading === video.name}
                  className="px-4 py-2 bg-red-600 hover:bg-red-700 disabled:bg-red-600/50 text-white rounded-lg transition-colors flex items-center gap-2"
                >
                  {uploading === video.name ? (
                    "Uploading..."
                  ) : (
                    <>
                      <span>📤</span> Upload
                    </>
                  )}
                </button>
                <button
                  onClick={() => deleteVideo(video)}
                  className="px-4 py-2 bg-white/10 hover:bg-red-600/50 text-white rounded-lg transition-colors"
                >
                  🗑️
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
